//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auteur
    {
        public Auteur()
        {
            this.Livres = new HashSet<Livre>();
        }
    
        public string idAut { get; set; }
        public string nomAuteur { get; set; }
        public string prenomAut { get; set; }
    
        public virtual ICollection<Livre> Livres { get; set; }
    }
}
