//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emprunteur
    {
        public Emprunteur()
        {
            this.Emprunts = new HashSet<Emprunt>();
        }
    
        public string numCarte { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string adresse { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<Emprunt> Emprunts { get; set; }
    }
}
