//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliv2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Exemplaire
    {
        public Exemplaire()
        {
            this.Emprunts = new HashSet<Emprunt>();
        }
    
        public string idEx { get; set; }
        public string reference { get; set; }
        public decimal anneEdition { get; set; }
        public string idliv { get; set; }
        public string idME { get; set; }
    
        public virtual ICollection<Emprunt> Emprunts { get; set; }
        public virtual MaisonEdition MaisonEdition { get; set; }
        public virtual Livre Livre { get; set; }
    }
}
