//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliv2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Livre
    {
        public Livre()
        {
            this.Exemplaires = new HashSet<Exemplaire>();
        }
    
        public string idliv { get; set; }
        public string titre { get; set; }
        public decimal anneeCrea { get; set; }
        public string descr { get; set; }
        public string idAut { get; set; }

        //gestion acces concurrents
        [Timestamp]
        public byte[] RowVersion { get; set; }
    
        public virtual Auteur Auteur { get; set; }
        public virtual ICollection<Exemplaire> Exemplaires { get; set; }
    }
}
